- src/browser/BrowserPage.cpp
QPainterPath is not used here.
Log:
> chore: remove unneeded header

- src/sidebar/ImageListview.cpp
> fix: build failures under Qt 5.14

- src/browser/BrowserPage.cpp
- src/document/Model.h
- src/document/PDFModel.cpp
- src/document/PDFModel.h
- src/document/PDFiumModel.h
Correct typos in parameters.
Log:
> chore: correct multiple typos

- reader/MainWindow.cpp
- reader/app/app.pri
- reader/app/eventlogutils.cpp
- reader/app/eventlogutils.h
> feat: 添加数据埋点

- 3rdparty/deepin-pdfium/src/dpdfannot.cpp
- 3rdparty/deepin-pdfium/src/dpdfpage.cpp
- reader/MainWindow.cpp
- reader/app/Utils.cpp
- reader/browser/BrowserPage.cpp
- reader/browser/SheetBrowser.cpp
- reader/document/Model.cpp
- reader/document/PDFModel.cpp
- reader/document/PDFModel.h
- reader/uiframe/Central.cpp
- reader/uiframe/CentralDocPage.cpp
- reader/uiframe/DocSheet.cpp
- reader/uiframe/SheetRenderer.cpp
Description: 由于网站链接路径转换错误
Log: 修复文档查看无法打开网站链接及添加一些关键日志打印
Bug: https://pms.uniontech.com/bug-view-154747.html
https://pms.uniontech.com/bug-view-154749.html
> fix: 修复文档查看无法打开网站链接及添加一些关键日志打印

- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/build/build_config.h
add rv64 support & cleanup sw64 duplicate definition
Signed-off-by: Han Gao <rabenda.cn@gmail.com>
> riscv64 & sw64: add rv64 support & cleanup sw64

- reader/sidebar/SideBarImageListview.cpp
Description: 修复页码数字会被遮挡一部分
Log: 修复页码数字会被遮挡一部分
> fix: 修复页码数字会被遮挡一部分

- reader/sidebar/SearchResWidget.cpp
- reader/uiframe/CentralNavPage.cpp
Description: 修复ui问题
Log: 修复ui问题
Bug: https://pms.uniontech.com/bug-view-157571.html
https://pms.uniontech.com/bug-view-157593.html
> fix: 修复ui问题

- reader/browser/SheetBrowser.cpp
- reader/widgets/TextEditWidget.cpp
Description: 由于注释编辑界面的最小高度设置不正确
Log: 修复窗口最小化，添加注释，注释输入框部分被遮挡
Bug: https://pms.uniontech.com/bug-view-142267.html
> fix: 修复窗口最小化，添加注释，注释输入框部分被遮挡

- .reuse/dep5
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/build/build_config.h
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/constants/access_permissions.h
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/constants/annotation_common.h
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/core/fpdfapi/edit/cpdf_creator.cpp
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/core/fpdfdoc/cpvt_wordinfo.cpp
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/core/fxcodec/jbig2/JBig2_DocumentContext.cpp
- 3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/core/fxcodec/jbig2/JBig2_DocumentContext.h
- 3rdparty/deepin-pdfium/src/dpdfannot.cpp
- 3rdparty/deepin-pdfium/src/dpdfdoc.cpp
- 3rdparty/deepin-pdfium/src/dpdfglobal.cpp
- 3rdparty/deepin-pdfium/src/dpdfpage.cpp
> fix: 开源合规整改

- reader/app/Utils.cpp
- reader/browser/BrowserPage.cpp
- reader/uiframe/DocSheet.cpp
Description: 修复文档查看器的日志记录了用户复制内容的问题
Log: 修复文档查看器的日志记录了用户复制内容的问题
Bug: https://pms.uniontech.com/bug-view-164929.html
> fix: 修复文档查看器的日志记录了用户复制内容的问题

- reader/document/Model.cpp
Description: 修复文档查看器无法打开附件中的docx文件
Log: 修复文档查看器无法打开附件中的docx文件
Bug: https://pms.uniontech.com/bug-view-165617.html
> fix: 修复文档查看器无法打开附件中的docx文件

- reader/Application.cpp
- reader/MainWindow.cpp
- reader/browser/PageRenderThread.cpp
- reader/browser/PageRenderThread.h
- reader/browser/SheetBrowser.cpp
- reader/browser/SheetBrowser.h
- reader/document/PDFModel.cpp
- reader/uiframe/Central.cpp
- reader/uiframe/CentralDocPage.cpp
- reader/uiframe/DocSheet.cpp
- reader/uiframe/DocTabBar.cpp
- reader/uiframe/SheetRenderer.cpp
- reader/uiframe/TitleWidget.cpp
Description: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字
Log: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字
Bug: https://pms.uniontech.com/bug-view-166397.html
> fix: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字

- deepin_reader.pro
- reader/uiframe/DocSheet.cpp
Description: Release版本不编译UT
Log: Release版本不编译UT
> chore: Release版本不编译UT

- 3rdparty/deepin-pdfium/src/src.pro
Description: 三方库安全编译参数
Log: 三方库安全编译参数
> chore: 三方库安全编译参数

- reader/MainWindow.cpp
- reader/MainWindow.h
- reader/uiframe/Central.cpp
- reader/uiframe/Central.h
- reader/uiframe/CentralDocPage.cpp
- reader/uiframe/CentralDocPage.h
- reader/uiframe/TitleMenu.h
Description: 上报当前打开的文档路径
Log: 上报当前打开的文档路径
Task: https://pms.uniontech.com/task-view-218115.html
> feat: 上报当前打开的文档路径

- reader/MainWindow.cpp
- reader/app/DBusObject.cpp
- reader/app/Utils.h
- reader/app/app.pri
- reader/reader.pro
合并release/eagle上的修改到master;添加系统版本判断，兼容V20与V23
Log: merge branch 'release/eagle' to 'master'
> fix: merge branch 'release/eagle' to 'master'

- reader/widgets/ScaleWidget.cpp
- reader/widgets/ScaleWidget.h
Description: 1060新增紧凑模式，未进行适配
Log: 修复紧凑模式下文档查看器顶部控件显示问题
Bug: https://pms.uniontech.com/bug-view-202837.html
> fix: 修复紧凑模式下文档查看器顶部控件显示问题

- reader/widgets/ScaleWidget.cpp
- reader/widgets/ScaleWidget.h
Description: 紧凑模式兼容性，增加对应的宏判断
Log: 紧凑模式兼容性，增加对应的宏判断
> chore: 紧凑模式兼容性，增加对应的宏判断

- debian/changelog
- reader/widgets/ScaleWidget.cpp
- reader/widgets/ScaleWidget.h
Description: 合并代码及更新changelog
Log: 合并代码及更新changelog
> chore: 合并代码及更新changelog

- .reuse/dep5
- reader/MainWindow.cpp
- reader/MainWindow.h
- reader/app/Utils.cpp
- reader/app/Utils.h
- reader/browser/SheetBrowser.cpp
- reader/load_libs.c
- reader/load_libs.h
- reader/src.pri
- reader/uiframe/CentralDocPage.cpp
- reader/uiframe/DocSheet.cpp
Description: zpd定制需求，复制拦截，关闭上报
Log: zpd定制需求，复制拦截，关闭上报
Task: https://pms.uniontech.com/task-view-279165.html
> feat: zpd定制需求，复制拦截，关闭上报

- reader/MainWindow.cpp
Description: 修改zpd测试库名称
Log: 修改zpd测试库名称
> chore: 修改zpd测试库名称

- debian/changelog
Description: 更新changelog（6.0.2）
Log: 更新changelog（6.0.2）
> chore: 更新changelog（6.0.2）

- reader/MainWindow.cpp
- reader/browser/SheetBrowser.cpp
- reader/sidebar/BookMarkWidget.cpp
- reader/sidebar/NotesWidget.cpp
- reader/sidebar/SheetSidebar.cpp
- reader/uiframe/CentralNavPage.cpp
- reader/uiframe/TitleWidget.cpp
- reader/widgets/FileAttrWidget.cpp
- reader/widgets/FindWidget.cpp
- reader/widgets/PagingWidget.cpp
- reader/widgets/SlidePlayWidget.cpp
- reader/widgets/SlideWidget.cpp
> fix: 适配紧凑模式

- reader/sidebar/BookMarkWidget.cpp
> fix: build failure on dtkgui 5.6.12

- debian/changelog
> chore: tag 6.0.6

- reader/MainWindow.cpp
- reader/main.cpp
optimized code
Log: optimized code
> fix: optimized code

- debian/changelog
change log 6.0.7
Log: change log 6.0.7
> fix: change log 6.0.7

- reader/uiframe/CentralDocPage.cpp
打开文件时，增加对文件夹（文档、图片）权限的判断
Log: 打开文件时，增加对文件夹（文档、图片）权限的判断
Bug: https://pms.uniontech.com/bug-view-237575.html
> fix: 修复文档查看器无权限访问文件时，提示错误

- debian/changelog
change log 6.0.8
Log: change log 6.0.8
> fix: change log 6.0.8

- debian/control
- reader/widgets/ShortCutShow.cpp
> fix: 适配1032编译与安装

- debian/changelog
change log 6.0.10
Log: change log 6.0.10
> fix: change log 6.0.10

- reader/app/Utils.cpp
- reader/app/Utils.h
- reader/main.cpp
Adapt Treeland, disable wayland settings in
Treeland enviroment.
Log: Adapt Treeland.
Influence: Treeland
> feat: adapt treeland

- reader/MainWindow.cpp
- reader/app/Utils.cpp
- reader/load_libs.c
- reader/uiframe/CentralDocPage.cpp
- reader/uiframe/DocSheet.cpp
Optimize startup failure problem
Log: Optimize startup failure problem
Task: https://pms.uniontech.com/task-view-361175.html
> fix: Optimize startup failure problem

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
v6.5.1 release.
Log: v6.5.1 release.
> chore: new version 6.5.1

- arm64/linglong.yaml
- linglong.yaml
update linglong version with changelog.
Log: pdate linglong version.
> chore: update linglong version

- 3rdparty/deepin-pdfium/src/src.pro
- arm64/linglong.yaml
- deploy_dep
- linglong.yaml
Sync the id version as deb version, and slimming down the linglong layer package.
Log: Linglong installation package slimming down.
> chore: [linglong]The installation package slimming down

- deepin_reader.pro
Disable test for special arch, which may block CI.
Log: Fix build for special arch.
> fix: [build]Disable test for special arch

- debian/changelog
- debian/rules
Fix pdf conflict problem
Log: fix pdf conflict problem
> chore: Fix pdf conflict problem

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
Bump version to 6.5.6
Log: Bump version to 6.5.6
> chore: Bump version to 6.5.6

- arm64/linglong.yaml
- linglong.yaml
Update linglong.yaml for new runtime.
Log: Update linglong.yaml for new runtime
> chore: update linglong.yaml for new runtime

- arm64/linglong.yaml
- linglong.yaml
- loong64/linglong.yaml
fix no help manual for app.
Log: fix no help manual for app
> fix: fix no help manual for app

- debian/control
> fix: control update

- debian/changelog
> fix: Release to unstable.

- arm64/linglong.yaml
- debian/changelog
- install_dep
- linglong.yaml
- loong64/linglong.yaml
Update linglong.yaml for qt6.8 runtime.
Log: Update linglong.yaml for qt6.8 runtime
> chore: update linglong.yaml for qt6.8 runtime

- deepin_reader.pro
- translate_generation.sh
Log: fix: Add translation function
> fix: Add translation function

- 3rdparty/deepin-pdfium/src/dpdfdoc.cpp
As title.
Log: fix a dead lock issue.
Bug: https://pms.uniontech.com/bug-view-304471.html
> fix: repeat lock() cause dead lock

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Bump version to 6.5.16
Log: Bump version to 6.5.16
> chore: Bump version to 6.5.16

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Start a new changelog entry.
Log: Start a new changelog entry.
> feat: Start a new changelog entry.

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Update version to 6.5.20
Log: Update version to 6.5.20
> chore: Update version to 6.5.20

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
Bump version to 6.5.21
Log: Bump version to 6.5.21
> chore: Bump version to 6.5.21

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
chore: update linglong.yaml
update linglong.yaml
log: update linglong.yaml
fix: https://pms.uniontech.com/bug-view-314071.html
> Bump version to 6.5.23 and update linglong.yaml

- reader/widgets/SlidePlayWidget.cpp
As title.
Log: Adapt to V23 dde dbus interface
> feat: Adapt to V23 dde dbus interface
