linuxdeepin/deepin-reader

reader/MainWindow.cpp
reader/browser/BrowserMagniFier.cpp
reader/browser/BrowserMenu.cpp
reader/browser/BrowserPage.cpp
reader/browser/BrowserPage.h
reader/browser/SheetBrowser.cpp
reader/document/DjVuModel.cpp
reader/uiframe/CentralDocPage.cpp
reader/uiframe/DocSheet.cpp
tests/browser/ut_browsermagnifier.cpp

Description: 有djvu底层库不能准确的识别到当前放大镜所在位置的图片
Log: 修复djvu格式文件，使用放大镜显示空白
Bug: https://pms.uniontech.com/bug-view-154771.html

fix: 修复djvu格式文件，使用放大镜显示空白

---

reader/uiframe/DocSheet.cpp

Description:  由于右侧文档显示界面重复刷新导致
Log:  修复docx格式，全屏或退出全屏时会自动跳到当前页的页首
Bug: https://pms.uniontech.com/bug-view-154723.html

fix: 修复docx格式，全屏或退出全屏时会自动跳到当前页的页首

---

reader/browser/SheetBrowser.cpp
reader/document/PDFModel.cpp

Description: 由于网站链接路径转换错误
Log: 修复文档查看无法打开网站链接及添加一些关键日志打印
Bug: https://pms.uniontech.com/bug-view-154749.html

fix: 修复docx文档查看无法打开网站链接

---

3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/core/fpdfapi/edit/cpdf_creator.cpp
reader/uiframe/DocSheet.cpp

Description: 修复附件中的文档，添加大量注释后快捷键保存，应用崩溃
Log: 修复附件中的文档，添加大量注释后快捷键保存，应用崩溃
Bug: https://pms.uniontech.com/bug-view-164325.html

fix: 修复附件中的文档，添加大量注释后快捷键保存，应用崩溃

---

reader/widgets/ShortCutShow.cpp

Description: 修复双屏时，查看快捷键面板时，面板位置不是居中显示
Log: 修复双屏时，查看快捷键面板时，面板位置不是居中显示
Bug: https://pms.uniontech.com/bug-view-164953.html

fix: 修复双屏时，查看快捷键面板时，面板位置不是居中显示

---

reader/browser/BrowserPage.cpp
reader/browser/BrowserPage.h
reader/browser/SheetBrowser.cpp
reader/document/PDFModel.cpp

Description: 未对书签区域做屏蔽
Log: 修复当书签与超链接重叠时，点击书签，会触发超链接
Bug: https://pms.uniontech.com/bug-view-164267.html

fix: 修复当书签与超链接重叠时，点击书签，会触发超链接

---

reader/uiframe/CentralDocPage.cpp
reader/uiframe/DocSheet.cpp

Description: 修复文档查看器打开多个文件后，仅关闭标签页，无法释放内存
Log: 修复文档查看器打开多个文件后，仅关闭标签页，无法释放内存
Bug: https://pms.uniontech.com/bug-view-164943.html

fix: 修复文档查看器打开多个文件后，仅关闭标签页，无法释放内存

---

reader/uiframe/DocSheet.cpp

修复打印预览保存图片为空问题
Bug: https://pms.uniontech.com/bug-view-219973.html
Log: 修复打印预览保存图片为空问题

fix: 修复打印预览保存图片为空问题

---

reader/widgets/ScaleWidget.cpp

修复文档查看器打开任意pdf，左上角未显示放大或缩小的百分比
Bug: https://pms.uniontech.com/bug-view-248095.html
Log: 修复文档查看器打开任意pdf，左上角未显示放大或缩小的百分比

fix: 修复文档查看器打开任意pdf，左上角未显示放大或缩小的百分比

---

reader/widgets/ShortCutShow.cpp

调整默认快捷键浮窗弹出位置.
现在将显示在焦点屏幕(光标所在屏幕)中央.
Log: 调整默认快捷键浮窗弹出位置
Task: https://pms.uniontech.com/task-view-332271.html
Influence: Shortcuts

feat: Change default shortcuts popup position

---

debian/changelog

Bump version to 6.0.9
PR:
* https://github.com/linuxdeepin/deepin-reader/pull/97
* https://github.com/linuxdeepin/deepin-reader/pull/98
Log: Bump version to 6.0.9

chore: Bump version to 6.0.9

---

reader/Application.cpp
reader/document/Model.cpp
reader/document/document.pri
reader/reader.pro
tests/tests.pro

The pandoc and htmltopdf are installed in other path by PREFIX defined, the patch fix its runtime issue. The webengine bin and resources must be copy into the same dir with htmltodpf installed path.
Log: fix runtime issue on linglong.

fix: Fix runtime issue on linglong box

---

reader/MainWindow.cpp
reader/uiframe/DocSheet.cpp

As title.
The previous fix bb8f3e921e4b3efe47f185b28164df3ef6f12613 worked for menu copy, but not for shortcut copy.
And 3fcf6f588aaf0e4755445bf7a8963bf9f458ff05 remove ZPD code by default.
Log: Fix shortcut copy text not work.
Bug: https://pms.uniontech.com/bug-view-234693.html
Influence: shortcut-copy

fix: shortcut copy text not work

---

deepin_reader.pro

Enable the testes only for x86_64 and aarch64 arch.
Log: Fix build for special arch.

fix: [build]Enable test only for amd64 and arm64

---

debian/changelog
deepin_reader.pro
reader/app/Utils.cpp
reader/app/Utils.h
reader/main.cpp

remove kwayland-shell env
Log: remove kwayland-shell env

fix: remove kwayland-shell env

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Update linglong.yaml for translations.
Log: Update linglong.yaml for translations

chore: update linglong.yaml for translations

---

.project
3rdparty/deepin-pdfium/include/dpdfglobal.h
3rdparty/deepin-pdfium/src/dpdfglobal.cpp
debian/control
debian/rules
reader/document/Model.cpp

Enable Qt6 build only for special arch, compat with qt5 build.
Log: Merge Qt5 and Qt6 build.

chore: Merge Qt5 and Qt6 build

---

.gitignore
debian/control
debian/rules
deepin_reader.pro
reader/reader.pro
reader/src.pri

Fix CI and remove unused dependency packages
Log: Fix CI and remove unused dependency package.

chore: Fix CI and remove unused dependency package

---

deepin_reader.pro
reader/app/DBusObject.cpp
reader/app/Utils.h
reader/reader.pro
reader/src.pri

Remove dframeworkdbus and use Dtk to get system info.
Log: Fix CI build with Qt5

fix: Fix CI build with Qt5

---

3rdparty/deepin-pdfium/src/3rdparty/pdfium/pdfium/build/build_config.h

feat: add rv64 support

---

arm64/linglong.yaml
debian/changelog
debian/control
linglong.yaml
loong64/linglong.yaml

Update the version of deepin-reader to 6.5.19 in all relevant files and add a new dependency for libqt6webenginecore6-bin. Update changelog accordingly.

chore: Bump version to 6.5.19 and update dependencies

---

3rdparty/deepin-pdfium/src/src.pro
arm64/linglong.yaml
linglong.yaml
loong64/linglong.yaml
reader/src.pri

The conflict between deepin-pdfium library and file manager installation, modify the name to avoid this issue.
Log: Rename pdf library.

fix: Rename pdf library

---

reader/MainWindow.cpp
reader/app/DBusObject.cpp

Convert url to local path.
Log: support url.
Bug: https://pms.uniontech.com/bug-view-312013.html

fix: support url

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.22
Log: Bump version to 6.5.22

chore: Bump version to 6.5.22

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

chore: Update package URLs and digests in linglong.yaml files
- Updated coreutils and cryfs package URLs and digests across all architectures.
log: Update package URLs and digests in linglong.yaml files

chore: Update package URLs and digests in linglong.yaml files

---

arm64/linglong.yaml
debian/changelog
htmltopdf/htmltopdf.pro
linglong.yaml
loong64/linglong.yaml
reader/reader.pro
translations/deepin-reader_lo.ts
translations/desktop/desktop_lo.ts

- update version to 6.5.33
log: update version to 6.5.33

chore: Update version to 6.5.33

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

- update version to 6.5.40
log: update version to 6.5.40

chore: Update version to 6.5.40
